### ISSUE TITLE
sbt compile fails

### ISSUE THREAD

**Issue by akhil** [eligosource/eventsourced#128]
When I checkout master and run 'sbt compile' it fails.

[info] Resolving org.reactivemongo#reactivemongo_2.10;0.9-AKKA-2.2.0-RC1-SNAPSHO[info] Resolving org.reactivemongo#reactivemongo-bson-macros_2.10;0.9-AKKA-2.2.0[info] Resolving org.reactivemongo#reactivemongo-bson_2.10;0.9-AKKA-2.2.0-RC1-SN[info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
[info] Done updating.
[info] Resolving org.eligosource#eventsourced-journal-common_2.10;0.6-SNAPSHOT .[info] Resolving com.typesafe.akka#akka-actor_2.10;2.2.0-RC1 ...
[warn] Potentially incompatible versions of dependencies of {file:/home/akhil/github/eventsourced/}eventsourced-journal-mongodb-reactive:
[warn]    org.scala-lang: 2.10.1, 2.10.0
[info] Resolving com.sclasen#spray-dynamodb_2.10;0.2.0-SNAPSHOT ...
sbt appears to be exiting abnormally.
  The log file for this session is at /tmp/sbt923506069926769063.log
Exception in thread "main" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
Exception in thread "Keep-Alive-Timer" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Keep-Alive-Timer"

**Comment by ironfish** [comment]
Hi @akhil, it looks like your getting a java.lang.OutOfMemoryError. I just compiled and everything worked fine. Try increasing your SBT memory setting in your .sbtconfig. Here are my settings:

`SBT_OPTS="-Xms512m -Xmx2048m -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512m -XX:+UseCodeCacheFlushing"`

Cheers,

**Comment by akhil** [comment]
@ddevore that solves it. Thank you

**Comment by ironfish** [comment]
@akhil Great! Glad I could help.
