### ISSUE TITLE
MapDB | Disruptor

### ISSUE THREAD

**Issue by sirinath** [eligosource/eventsourced#133]
Hi,

Perhaps you can use MapDB for Journalling. Also perhaps using Disruptor for channels and mailboxes.

Disruptor may speed up thing with SSD for journals storage and for un reliable channel. Also look at https://github.com/epickrram/disruptor-proxy.

S

**Comment by sirinath** [comment]
Also pluggable transport mechanism and mail boxes would be helpful.

**Comment by krasserm** [comment]
Pull requests gratefully received ;-)
