### ISSUE TITLE
Can use ReactiveMongo 0.10-SNAPSHOT for journal

### ISSUE THREAD

**Issue by lshoo** [eligosource/eventsourced#140]
Hello,
Is the MongoDB Reactive based journal still developing now?
Can I use latest ReactiveMongo(now is 0.10-SNAPSHOT)  for mongo reactive journal with eventsourced?

Thanks!

Best Regards
tiGer

**Comment by ironfish** [comment]
Hi tiGer,

Yes, you can use the latest version of the journal. I would use
release-0.6. That being said however the mongo journal for Akka-Persistence
should be out by the end of the year. Akka-Persistence is a replacement for
Eventsourced and is what I would recommend you should go with.

Cheers,

On Wed, Dec 11, 2013 at 1:05 AM, lshoo notifications@github.com wrote:

> Hello,
> Is the MongoDB Reactive based journal still developing now?
> Can I use latest ReactiveMongo(now is 0.10-SNAPSHOT) for mongo reactive
> journal with eventsourced?
> 
> Thanks!
> 
> Best Regards
> tiGer
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eligosource/eventsourced/issues/140
> .

## 

Duncan K. DeVore
<><

**Comment by lshoo** [comment]
Thanks DeVore!
I  try akka-persistence with akka 2.3 too, I want to use it now but akka-2.2 or old version have not akka-persistence module.

Best  Regard
tiGer

**Comment by krasserm** [comment]
@lshoo can we close this issue?

**Comment by lshoo** [comment]
Thanks

CLOSE now 

Best Regard
tiGer
