### ISSUE TITLE
UnsadisfiedLinkError on Windows

### ISSUE THREAD

**Issue by wir33658** [eligosource/eventsourced#23]
Hi, I am not sure if this is the right place.

I checked out the recent wip-akka-2.1 branch. Started SBT and did a compile. So far looks fine but running  "test:run-nobootcp org.eligosource.eventsourced.guide.FirstSteps" I get

> about
> [info] This is sbt 0.12.1
> [info] The current project is {file:/D:/Development/Playground/EventSourced/wip-
> aka-2_1/eventsourced/}eventsourced
> [info] The current project is built against Scala 2.10.0-RC2
> [info] Available Plugins: org.sbtidea.SbtIdeaPlugin
> [info] sbt, sbt plugins, and build definitions are using Scala 2.9.2
> 
> test:run-nobootcp org.eligosource.eventsourced.guide.FirstSteps
> [warn] Credentials file C:\Users\Weissmann.sbt.credentials does not exist
> Uncaught error from thread [guide-akka.actor.default-dispatcher-3] shutting down
>  JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[guide]
> java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni3
> 2-1.2 in java.library.path, no leveldbjni-1.2 in java.library.path, no leveldbjn
> i in java.library.path]
>         at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:184)
>         at org.fusesource.hawtjni.runtime.Library.load(Library.java:142)
>         at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)
>         at org.eligosource.eventsourced.journal.LeveldbJournalPS.<init>(LeveldbJournalPS.scala:47)
>         at org.eligosource.eventsourced.journal.LeveldbJournal$$anonfun$processorStructured$2.apply(LeveldbJournal.scala:45)
>         at org.eligosource.eventsourced.journal.LeveldbJournal$$anonfun$processorStructured$2.apply(LeveldbJournal.scala:45)
>         at akka.actor.ActorCell.newActor(ActorCell.scala:456)
>         at akka.actor.ActorCell.create(ActorCell.scala:474)
>         at akka.actor.ActorCell.systemInvoke(ActorCell.scala:346)
>         at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:256)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:211)
>         at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
> [trace] Stack trace suppressed: run last *:run-nobootcp for the full output.
> [error](*:run-nobootcp) Run failed
> [error] Total time: 2 s, completed 09.11.2012 13:57:05

**Comment by krasserm** [comment]
This is now fixed in branch wip-akka-2.1 after an upgrade to leveldbjni 1.4.1. Earlier versions didn't support Windows.
