### ISSUE TITLE
General question on channel names

### ISSUE THREAD

**Issue by wir33658** [eligosource/eventsourced#26]
Hi, I am new to this, so this might make no sense at all, but is it possible to use wildcards for a channel ? 

I try to figure out if the following scenario is possible in this environment (like in akka-camel, there it is possible) :

Publish - Subscribe with Wildcards :

extension.channelOf(DefaultChannelProps(1, listener1).withName("level1.level2.level3.*"))
extension.channelOf(DefaultChannelProps(2, listener2).withName("level1.>"))
extension.channelOf(DefaultChannelProps(3, listener3).withName("level1.level2.level3.level4"))

....

emitter("level1") sendEvent AnyEvent                                         -> listener2 acts

....

emitter("level1.level2.level3.level5") sendEvent AnyEvent     -> listener1 and listener2 acts

....

Cheers, Rob.

**Comment by krasserm** [comment]
Please use the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/eventsourced) for questions.
