### ISSUE TITLE
Add OSGi meta-data to the jar

### ISSUE THREAD

**Issue by rocketraman** [eligosource/eventsourced#32]
I would like to use eventsourced in an OSGi environment. I was able to add the OSGi meta-data to both leveldbjni, and eventsourced, and make it work correctly. However, it would be great if this could be applied upstream.

Unfortunately, the sbt-osgi plugin seems to be very flaky -- see my post here on the sbt mailing list as I could not get sbt to add the OSGi meta-data:

https://groups.google.com/d/msg/simple-build-tool/LC0rLHK2jfc/du8os8wmxE0J

I will continue to follow up on this and submit a pull request once I have it working.

**Comment by krasserm** [comment]
Thanks a lot, Raman, highly appreciate your initiative. Please bear in mind that I'll make eventsourced a multi-module project in the near future (e.g. moving out journal impls into separate sub-projects). Maybe I then need to ask you for help again, getting the OSGi metadata right in the multi-module project.

Cheers,
Martin

**Comment by rocketraman** [comment]
No problem, glad to help.

**Comment by rocketraman** [comment]
See https://github.com/eligosource/eventsourced/pull/34

**Comment by rocketraman** [comment]
GitHub opened a new issue #34 when I submitted the pull... please continue discussion there.
