### ISSUE TITLE
Please publish for Scala 2.10.0-RC2 and Akka 2.1.0-RC2 built with JVM 6. :-)

### ISSUE THREAD

**Issue by ghost** [eligosource/eventsourced#38]
The subject says it all: we're seeing

java.lang.UnsupportedClassVersionError: org/eligosource/eventsourced/core/JournalProtocol$CommandProtocol : Unsupported major.minor version 51.0

at runtime using the recently-published 0.5-SNAPSHOT for Scala 2.10.0-RC2 and Akka 2.1.0-RC2 (thanks again for that)!

**Comment by krasserm** [comment]
This is fixed now. Thanks for reporting!
