### ISSUE TITLE
Develop as Part of TypeSafe Stack

### ISSUE THREAD

**Issue by sirinath** [eligosource/eventsourced#40]
Hi,

Is it possible to develop this as part of type safe like Slick? Perhaps you could convince them to take this on.

S

P.S. I believe is it best to make the production journal an embeddable pure Java implementations. Perhaps even implement one as part of the project itself.

**Comment by krasserm** [comment]
I don't think that this should go the the eventsourced issue tracker. What's the problem if it's not part of the Typesafe stack? Why don't you discuss that on the Akka mailing list?
