### ISSUE TITLE
Create a Java API for eventsourced

### ISSUE THREAD

**Issue by astubbs** [eligosource/eventsourced#63]
Would be great for us living in Java API AKKA land, would be great to get a way to use EventSourced from Java.

**Comment by sneakybeaky** [comment]
amen to that

**Comment by dispalt** [comment]
+1

**Comment by jboner** [comment]
Excellent idea. :+1:

**Comment by pditommaso** [comment]
+1

**Comment by hannesstockner** [comment]
+1

**Comment by ersiner** [comment]
+1

**Comment by krasserm** [comment]
Ok guys, I'll see what I can do when starting to work on 0.6-SNAPSHOT.

**Comment by johanhaleby** [comment]
+1

**Comment by krasserm** [comment]
Summary of current state [here](https://groups.google.com/forum/#!msg/eventsourced/3rHOojAdSTI/zs7F9g_ckQEJ). Further work on the Java API will be tracked by other tickets.
