### ISSUE TITLE
ReliableRequestReplyChannelProps not found. 

### ISSUE THREAD

**Issue by duskhacker** [eligosource/eventsourced#64]
I cannot seem to get the compiler to recognize this class. I've gone so far as to put the code from http://krasserm.blogspot.com/2013/01/event-sourcing-and-external-service.html, which works fine in the eventsourced tree, into my project, and it still isn't recognized. 

I'm using the latest snapshots 2.10 snapshots from http://repo.eligotech.com/nexus/content/repositories/eligosource-snapshots and have accounted for the split into core/journal done recently. 

I'm a Scala/Java newb, so I may just be doing something dumb, but it looks like it should work, everything else does.

**Comment by krasserm** [comment]
Hi Daniel, 

the eventsourced project has been refactored into a multi-module project in the meantime. See also [this announcement](https://groups.google.com/forum/?fromgroups=#!topic/eventsourced/6zXcGiuT7VY). The [example](https://github.com/eligosource/eventsourced/blob/master/es-examples/src/main/scala/org/eligosource/eventsourced/example/OrderExampleReliable.scala) is now located in the [eventsourced-examples](https://github.com/eligosource/eventsourced/tree/master/es-examples) module. You can run it under sbt with

```
> project eventsourced-examples
> run-main org.eligosource.eventsourced.example.CreditCardValidator
```

in one JVM. I a second JVM run

```
> project eventsourced-examples
> run-main org.eligosource.eventsourced.example.OrderProcessor
```

Another change was that the `ReliableRequestReply` trait must now be extended explicitly. I'll update the blog post soon. 

Cheers,
Martin

**Comment by krasserm** [comment]
Blog post updated. Sorry for the inconvenience.

**Comment by krasserm** [comment]
Had to make [another change](https://github.com/eligosource/eventsourced/commit/4bc990114eeeeeab3d468dac2f5675320635f693). To use reliable request reply, just import

```
import org.eligosource.eventsourced.patterns.reliable.requestreply._
```

and you're done. This should stay now as is.
